apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    results.tekton.dev/record: pipelines-tutorial/results/6393a49c-dd4e-4b8a-9993-69ff1ce8e1ca/records/6393a49c-dd4e-4b8a-9993-69ff1ce8e1ca
    results.tekton.dev/result: pipelines-tutorial/results/6393a49c-dd4e-4b8a-9993-69ff1ce8e1ca
    results.tekton.dev/stored: "true"
  creationTimestamp: "2025-07-29T07:00:15Z"
  finalizers:
  - chains.tekton.dev/pipelinerun
  - results.tekton.dev/pipelinerun
  generateName: build-deploy-api-pipelinerun-
  generation: 1
  labels:
    tekton.dev/pipeline: build-and-deploy
  name: build-deploy-api-pipelinerun-km6bx
  namespace: pipelines-tutorial
  resourceVersion: "77955"
  uid: 6393a49c-dd4e-4b8a-9993-69ff1ce8e1ca
spec:
  params:
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api
  - name: deployment-name
    value: pipelines-vote-api
  - name: git-url
    value: https://github.com/openshift/pipelines-vote-api.git
  pipelineRef:
    name: build-and-deploy
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: source-pvc
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
      status: {}
status:
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: build-deploy-api-pipelinerun-km6bx-fetch-repository
    pipelineTaskName: fetch-repository
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: build-deploy-api-pipelinerun-km6bx-build-image
    pipelineTaskName: build-image
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: build-deploy-api-pipelinerun-km6bx-apply-manifests
    pipelineTaskName: apply-manifests
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: build-deploy-api-pipelinerun-km6bx-update-deployment
    pipelineTaskName: update-deployment
  completionTime: "2025-07-29T07:02:40Z"
  conditions:
  - lastTransitionTime: "2025-07-29T07:02:40Z"
    message: 'Tasks Completed: 4 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - description: name of the deployment to be patched
      name: deployment-name
      type: string
    - description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: master
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - description: image to be build from the code
      name: IMAGE
      type: string
    tasks:
    - name: fetch-repository
      params:
      - name: URL
        value: https://github.com/openshift/pipelines-vote-api.git
      - name: SUBDIRECTORY
        value: ""
      - name: DELETE_EXISTING
        value: "true"
      - name: REVISION
        value: master
      taskRef:
        params:
        - name: kind
          value: task
        - name: name
          value: git-clone
        - name: namespace
          value: openshift-pipelines
        resolver: cluster
      workspaces:
      - name: output
        workspace: shared-workspace
    - name: build-image
      params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api
      runAfter:
      - fetch-repository
      taskRef:
        params:
        - name: kind
          value: task
        - name: name
          value: buildah
        - name: namespace
          value: openshift-pipelines
        resolver: cluster
      workspaces:
      - name: source
        workspace: shared-workspace
    - name: apply-manifests
      runAfter:
      - build-image
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
      - name: source
        workspace: shared-workspace
    - name: update-deployment
      params:
      - name: deployment
        value: pipelines-vote-api
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api
      runAfter:
      - apply-manifests
      taskRef:
        kind: Task
        name: update-deployment
    workspaces:
    - name: shared-workspace
  provenance:
    featureFlags:
      awaitSidecarReadiness: true
      coschedule: workspaces
      enableAPIFields: beta
      enableProvenanceInStatus: true
      enforceNonfalsifiability: none
      maxResultSize: 4096
      resultExtractionMethod: termination-message
      runningInEnvWithInjectedSidecars: true
      verificationNoMatchPolicy: ignore
  startTime: "2025-07-29T07:00:15Z"
